repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
rev: v4.4.0
hooks:
- id: end-of-file-fixer
- id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint.git
rev: v1.32.0
hooks:
- id: yamllint
- repo: https://github.com/yannh/kubeconform
rev: v0.6.4
hooks:
- id: kubeconform
name: kubeconform (validate k8s manifests)
entry: kubeconform
language: go
types: [yaml]
args: ["-strict", "-summary"]
- repo: https://github.com/zricethezav/gitleaks
rev: v8.18.2
hooks:
- id: gitleaks
name: gitleaks (detect secrets)
entry: gitleaks detect --no-git -v --config=.gitleaks.toml
language: go
types: [yaml, json, dotenv]